### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by mec-kon** [DeebotUniverse/client.py#120]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

I have installed the library with pip install deebot-client .
When I start the sample code from the readme I get the following error: 
` File "/home/.../env/lib/python3.8/site-packages/.../logging_filter.py", line 12, in SanitizeFilter
    _SANITIZE_LOG_KEYS: set[str] = {
TypeError: 'type' object is not subscriptable`

### On which deebot vacuum you have the issue?

Deebot Ozmo 920

### Which version of the deebot-client are you using?

1.4.0

### Country

de

### Continent

eu

**Comment by edenhaus** [comment]
I cannot reproduce your issue. When I run the code from the readme, it works correctly and the vacuum starts cleaning.

**Comment by edenhaus** [comment]
Closing due inactivity

**Comment by jaxzin** [comment]
For anyone hitting this using Python 3.8, I fixed this by upgrading to Python 3.10.
