### ISSUE TITLE
Trying to get data from GOAT G1 mower

### ISSUE THREAD

**Issue by dogmatic69** [DeebotUniverse/client.py#260]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

example code in the readme does not work, cant import the required packages. 

### On which deebot vacuum you have the issue?

na

### Which version of the deebot-client are you using?

1.6.1

### Country

se

### Continent

eu

### Anything in the logs that might be useful for us?

```txt
python /code/main.py 
Traceback (most recent call last):
  File "/code/main.py", line 12, in <module>
    from deebot_client.mqtt_client import MqttClient, MqttConfiguration
ImportError: cannot import name 'MqttConfiguration' from 'deebot_client.mqtt_client' (/usr/local/lib/python3.10/site-packages/deebot_client/mqtt_client.py)
root@99dc47ae7630:/# pip list
Package            Version
------------------ -------
aiohttp            3.8.4
aiosignal          1.3.1
async-timeout      4.0.2
attrs              23.1.0
cachetools         5.3.1
charset-normalizer 3.1.0
deebot-client      1.6.1
frozenlist         1.3.3
gmqtt              0.6.12
idna               3.4
multidict          6.0.4
numpy              1.24.3
Pillow             9.5.0
pip                23.0.1
setuptools         65.5.1
wheel              0.40.0
yarl               1.9.2

[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: pip install --upgrade pip
root@99dc47ae7630:/# python --version
Python 3.10.11
```

**Comment by dogmatic69** [comment]
Removed mqtt and then had other auth errors. Found pypi is better example https://pypi.org/project/deebot-client/

**Comment by edenhaus** [comment]
The main branch is used like as development branch. To use the example on the branch you need also use the source code directly. At the time of writing this comment, you need the version `2.0.0b3`.
On pypi you find the example for last stable version.

Please note that this library is supporting mainly vacuum robots and I don't know if the G1 will work with this library. Please provide me with feedback

**Comment by dogmatic69** [comment]
it works with g1

**Comment by dogmatic69** [comment]
considering the issue is main being a newer version, can close this.
