### ISSUE TITLE
Port to official HA integration

### ISSUE THREAD

**Issue by JohannesPtaszyk** [DeebotUniverse/client.py#262]
### Question

Does it make sense to start discussions about porting this custom integration to the official HA integration, so everyone can benefit from a better version, as official integration is using sucks, which is not well maintained and does not work properly.

**Comment by edenhaus** [comment]
I have moved it :)

When can also call when you have time, also in two weeks :)

**Comment by edenhaus** [comment]
@JohannesPtaszyk Do you have time for a quick call next week?

**Comment by JohannesPtaszyk** [comment]
Hey, just came back from Droidcon yesterday, I think I would have time, are you on discord? Maybe we can find a slot.

**Comment by edenhaus** [comment]
@JohannesPtaszyk Contact me on Discord. My username is `edenhaus`
