### ISSUE TITLE
AttributeError: 'ProactorEventLoop' object has no attribute 'add_reader'

### ISSUE THREAD

**Issue by StefanoGiu** [DeebotUniverse/client.py#300]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

Not working on Windows:

ERROR:deebot_client.mqtt_client:An exception occurred
Traceback (most recent call last):
  File "XXX\Python311\Lib\site-packages\deebot_client\mqtt_client.py", line 160, in mqtt
    async with (await self._get_client()) as client:
  File "XXX\Python311\Lib\site-packages\aiomqtt\client.py", line 1070, in __aenter__
    await loop.run_in_executor(
  File "XXX\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "XXX\Python311\Lib\site-packages\paho\mqtt\client.py", line 914, in connect
    return self.reconnect()
           ^^^^^^^^^^^^^^^^
  File "XXX\Python311\Lib\site-packages\paho\mqtt\client.py", line 1086, in reconnect
    self._call_socket_open()
  File "XXX\Python311\Lib\site-packages\paho\mqtt\client.py", line 2155, in _call_socket_open
    on_socket_open(self, self._userdata, self._sock)
  File "XXX\Python311\Lib\site-packages\aiomqtt\client.py", line 1021, in _on_socket_open
    self._loop.call_soon_threadsafe(self._loop.add_reader, sock.fileno(), callback)
                                    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ProactorEventLoop' object has no attribute 'add_reader'

### On which deebot vacuum you have the issue?

Deebot X1 Omni

### Which version of the deebot-client are you using?

3.0.0

### Country

it

### Continent

eu

### Anything in the logs that might be useful for us?

```txt
AttributeError: 'ProactorEventLoop' object has no attribute 'add_reader'
```

### Additional information

AttributeError: 'ProactorEventLoop' object has no attribute 'add_reader'

**Comment by edenhaus** [comment]
Currently, Windows is not supported by the mqtt library used by this library.

How do you use this library?

**Comment by StefanoGiu** [comment]
I use it via Home Assistant

**Comment by edenhaus** [comment]
Home Assistant does not support native Windows installation without WSL, same as this integration. Please see https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/issues/364
