### ISSUE TITLE
Add support for ECOVACS DEEBOT TEO OMNI

### ISSUE THREAD

**Issue by rivendellstuff** [DeebotUniverse/client.py#343]
cant seem to find a state or button for it. I have it running a few times a day in the same room where cats litter box is but I dont want it mopping 4 times a day. Would be nice to be able to dynamically control that.

ty

**Comment by edenhaus** [comment]
I transferred the issue to the client.py as it belongs here.

Do you have the technicalls skills to manually edit the manifest file?

**Comment by rivendellstuff** [comment]
possibly.
I guess I can copy [this one](https://github.com/DeebotUniverse/client.py/blob/dev/deebot_client/hardware/deebot/p1jij8.py) and see if it just works first and tweak from there

**Comment by rivendellstuff** [comment]
yeah I guess I donno how to add it. I didnt realize this client repo was different from the [Deebot-4-Home-Assistant](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/tree/dev) which is what I have installed in HA. 

I looked around but I'm not sure what to do next. The T20 file has the same options my app shows though.  This in particular is what I'm after: 

![image](https://github.com/DeebotUniverse/client.py/assets/128875345/6868a834-3528-4a66-af7a-be11f6dd2b9b)

I dont mind doing the work if theres ome steps I can follow.

**Comment by edenhaus** [comment]
If your bot have the same capabilities as the T20 than create a symbolic link for you class to the t20 class. Create a pull request for it and I'm happy to.merge it

**Comment by rivendellstuff** [comment]
I tried adding a branch to dev and main. It just says I dont have write access and that I should fork it.

**Comment by edenhaus** [comment]
Yes, please fork the repository and make your changes. Afterwards open a pullrequest and I will review it and merge it in

**Comment by rivendellstuff** [comment]
all I did was make the symlink, not sure if theres more updates that need to be done.  looksl ike it failed some pipeline checks. 

https://github.com/DeebotUniverse/client.py/pull/359

**Comment by rivendellstuff** [comment]
did I update it incorrectly? 
the model I have is:  85nbtp

is that not what needs to be added ? looks like it was changed?

**Comment by rivendellstuff** [comment]
@edenhaus 

thank you! its working as expected now.

![image](https://github.com/DeebotUniverse/client.py/assets/128875345/2ace926c-b754-4768-affe-7eeeffc221fa)
