### ISSUE TITLE
Add support for Windows users

### ISSUE THREAD

**Issue by StefanoGiu** [DeebotUniverse/client.py#391]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

Since Python 3.8, the default asyncio event loop is the ProactorEventLoop. Said loop [doesn't support the add_reader method](https://docs.python.org/3/library/asyncio-platforms.html#windows) that is required by aiomqtt. Please switch to an event loop that supports the add_reader method such as the built-in SelectorEventLoop:

# Change to the "Selector" event loop if platform is Windows
if sys.platform.lower() == "win32" or os.name.lower() == "nt":
    from asyncio import set_event_loop_policy, WindowsSelectorEventLoopPolicy
    set_event_loop_policy(WindowsSelectorEventLoopPolicy())
# Run your async application as usual
asyncio.run(main())

### On which deebot device (vacuum) you have the issue?

Deebot X1 Omni

### Which version of the deebot-client are you using?

4.1.0

### Country

it

### Continent

eu

### Anything in the logs that might be useful for us?

```txt
# Change to the "Selector" event loop if platform is Windows
if sys.platform.lower() == "win32" or os.name.lower() == "nt":
    from asyncio import set_event_loop_policy, WindowsSelectorEventLoopPolicy
    set_event_loop_policy(WindowsSelectorEventLoopPolicy())
# Run your async application as usual
asyncio.run(main())
```

**Comment by edenhaus** [comment]
I don't have plans to add support for Windows, but feel free to add it.
Relates to https://github.com/DeebotUniverse/client.py/issues/300

**Comment by edenhaus** [comment]
Please add the workaround to the readme if you want, but there is no need to change anything in the library as selecting and starting the event loop is done by the caller of the library and not by the library itself
