### ISSUE TITLE
Add support for  Deebot T9 AIVI (8kwdb4)

### ISSUE THREAD

**Issue by townsmcp** [DeebotUniverse/client.py#607]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

As per the new Home Assistant 2024.12.x dropping devices unrecognised by the library, my Deebot T9 AIVI is no longer being detected. Hopefully I am getting ahead of the curve by being on the HA beta! I am not skilled enough to reverse engineer as per the HA integration statement of `This reverse engineering can only be done by persons, who are in possession of such a device and the knowledge how to do the reverse engineering`.

### On which deebot device (vacuum) you have the issue?

Deebot T9 AIVI

### Which version of the deebot-client are you using?

HA 2024.12.0b4

### Country

China (I believe, its been working for a long time, its an AliExpress bot)

### Continent

China (I believe, its been working for a long time, its an AliExpress bot)

### Anything in the logs that might be useful for us?

```txt
Logs show the following:

Device "DEEBOT T9 AIVI" not supported. Please add support for it to https://github.com/DeebotUniverse/client.py: {'did': 'a2a0d809-474b-4078-9beb-de26b94140a1', 'name': 'E04P14837C09HHST0141', 'class': '8kwdb4', 'resource': 'eZy7', 'company': 'eco-ng', 'bindTs': 1697007730203, 'service': {'jmq': 'jmq-ngiot-cn.dc.cn.ecouser.net', 'mqs': 'api-ngiot.dc-cn.cn.ecouser.net'}, 'deviceName': 'DEEBOT T9 AIVI', 'icon': 'https://portal.ecouser.net/api/pim/file/get/603f50488da56e0008ce7cb7', 'ota': True, 'UILogicId': 'T9_AF', 'materialNo': '110-2011-0001', 'pid': '5f963160b789620008056feb', 'product_category': 'DEEBOT', 'model': 'T9_AIVI_AF', 'updateInfo': {'needUpdate': False, 'changeLog': ''}, 'nick': 'Deebot', 'homeId': '6260fa7a4f20d923f824fdd0', 'homeSort': 9999, 'status': 1, 'offmap': True, 'otaUpgrade': {}}
```
Also, I enabled logging, reloaded integration and got the following log file:
[home-assistant_ecovacs_2024-12-04T08-15-11.996Z.log](https://github.com/user-attachments/files/18004720/home-assistant_ecovacs_2024-12-04T08-15-11.996Z.log)

Also adding this:

[config_entry-ecovacs-98f4723e7eba7d88efe639eae24c5666.json](https://github.com/user-attachments/files/18006664/config_entry-ecovacs-98f4723e7eba7d88efe639eae24c5666.json)

```


### Additional information

All entities are still showing in HA, just now set to `Unavailable`:
![image](https://github.com/user-attachments/assets/27f7377e-edd2-47c8-b4d4-dd72d179be2b)
![image](https://github.com/user-attachments/assets/e51281a2-2285-4f08-af07-c90897aba075)
![image](https://github.com/user-attachments/assets/29ff9423-357d-4830-a748-c66c9b04bd9b)
![image](https://github.com/user-attachments/assets/0c0b60f1-b392-4081-9ad3-d1b652da5454)

**Comment by Benjamin45590** [comment]
Same issue with X1e Omni

**Comment by edenhaus** [comment]
See https://github.com/DeebotUniverse/client.py/issues/612

**Comment by BloodyusHellus** [comment]
I'd also like the T9 AIVI to be added. I read #612 although am not skilled enough to follow these instructions since I never did a PR in github before. I do, however, own the T9 AIVI so if someone could point me to some more specific directions as to how I could test/fix this myself I'd certainly be willing to help.
I suspect functions of the T9 AIVI are pretty similar tot T10 Omni but since I don't own both I can't be sure.

**Comment by townsmcp** [comment]
Thank you @edenhaus. I have read the linked article. Just one question though regarding the line `If yes, create a symbolic link between your model and a similar one` - I am assuming to do this you would use the addon `Terminal & SSH`? If so, what are the directories for the ecovacs files? I know to create symlinks you would use a command such as `ln -s /path/to/file /path/to/symlink`. When I `ls` from terminal addon I see the following:

![image](https://github.com/user-attachments/assets/ebf01d94-c3e6-4f2a-8a03-ecb0047ea150)

**Comment by marcolino7** [comment]
Hi,
I have a DEEBOT T9+ and I suspect is the same of AIVI an T10, I tried link suggested in #611 but I got an error.

Many thanks in advance

**Comment by townsmcp** [comment]
@marcolino7 what hardware code did you try?

**Comment by marcolino7** [comment]
> @marcolino7 what hardware code did you try? I am guessing 1vxt52 because of your error message stating `ModuleNotFoundError: No module named 'deebot_client.hardware.deebot.1vxt52'` which seems like an X1 Omni code from that other thread? I think you would need to create a .py file based on the hardware name of the T9+ (also, I THINK the model that I actually have is the T9+ as well which has the mopping attachment, scent thing when mopping isnt attached etc) so I will give it a try but probably wont be today

Hi @townsmcp ,
It take some time to get my mind clear on how this stuff works. So after I understood I use this command:

`ln -svfT p95mgv.py um2ywg.py `
The file p95mgv.py is T10 Plus and file um2ywg.py is my T9 Plus and seem they are compatible and now my T9 seem working fine. I have no competence to check that all commands are fine, but for now seems to work.
I suppose that at every Home Assistant Upgrade I need to retype the command until someone deploy a file for T9 Plus.
I have a question, is there a place with an updated list of supported robot?

Many thanks for your answer and your work here on this.

Marco

**Comment by marcolino7** [comment]
> @marcolino7 what hardware code did you try? I am guessing 1vxt52 because of your error message stating `ModuleNotFoundError: No module named 'deebot_client.hardware.deebot.1vxt52'` which seems like an X1 Omni code from that other thread? I think you would need to create a .py file based on the hardware name of the T9+ (also, I THINK the model that I actually have is the T9+ as well which has the mopping attachment, scent thing when mopping isnt attached etc) so I will give it a try but probably wont be today

I read that you have a T9+, so I am happy about, this means that it will be supported for sure :-D
I am in no hurry about this, please take your time, I have a workaround, my T9 is now cleaning my Kitchen so I  am happy.

Thanks

**Comment by marcolino7** [comment]
@townsmcp Small Update, 
linkng T9+ with T10+, get it work in Home Assistant. I get all command and also MAP, what I not see is the rooms:

![image](https://github.com/user-attachments/assets/97c9a4dc-6625-4070-8882-f4f3dc91b194)

I think this is a difference between 9 and 10. Waiting for an Update on T9+

Thanks

**Comment by Yterz** [comment]
I also have a T9 AIVI, but with a different class '659yh8', maybe because from Europe.

I made a PR for it, base on the Deebot OZMO T8 AIVI class 'x5d34r', as most likely all OZMO T8 T9 T10 many variants: #624.

Maybe it's relevant to do a grouped fallback for all those models ;)

**Comment by marcolino7** [comment]
> I also have a T9 AIVI, but with a different class '659yh8', maybe because from Europe.
> 
> I made a PR for it, base on the Deebot OZMO T8 AIVI class 'x5d34r', as most likely all OZMO T8 T9 T10 many variants: #624.
> 
> Maybe it's relevant to do a grouped fallback for all those models ;)

Hi I used a T10 as base for my T9 and rooms list in home assistant is empty. Do you have room list using T8 base settings? Thanks

**Comment by Yterz** [comment]
I rolled back to HA 2024.11.3 already, and using the default fallback I do have room list. I compared 8.4.1 Releases fallback.py to the T8 AVI x5d34r.py, and they appear to be identical.

It make sense that those models were the default one, as they were the foundation of the original integration https://github.com/And3rsL/Deebot-for-Home-Assistant

**Comment by townsmcp** [comment]
Thanks @Yterz - I can confirm the x5d34r.py is working for the 8kwd4, including room name. I will add a PR for this.
@marcolino7 definitely give it a go

**Comment by marcolino7** [comment]
> x5d34r.py

Hi @townsmcp,
thanks for your time. I will apply workaround for T8 on my T9 and waiting for releale. Do you know when it will be officially included in Home Assistant?

Thanks

**Comment by townsmcp** [comment]
> Hi @townsmcp,
> thanks for your time. I will apply workaround for T8 on my T9 and waiting for releale. Do you know when it will be officially included in Home Assistant?

@marcolino7 im not sure when it would be included in HA. However, I remember reading somewhere HA do weekly updates (on a Friday?) So fingers crossed this might make it to next Fridays update....if I have done what I need to correctly for @edenhaus to accept the PR

**Comment by marcolino7** [comment]
> > Hi @townsmcp,
> > thanks for your time. I will apply workaround for T8 on my T9 and waiting for releale. Do you know when it will be officially included in Home Assistant?
> 
> @marcolino7 im not sure when it would be included in HA. However, I remember reading somewhere HA do weekly updates (on a Friday?) So fingers crossed this might make it to next Fridays update....if I have done what I need to correctly for @edenhaus to accept the PR

Hi,
ok we will be all finger crossed :-D, meanwhile we have a workaround.
I just modified link with T8 instead T10 and I get room list.

Regards

**Comment by marcolino7** [comment]
Hi @townsmcp,
I created a specific PR for model T9+ um2ywg symlinking T8 AIVI x5d34r.py.

Regards

**Comment by xbmcnut** [comment]
Just in case anyone is trying to integrate this into HA 2026.3>, the `#` character also causes issues with your robot not being discovered returning a completely empty `devices: []` array. And although the app states your password must include special characters, it works without them.

N.B My robot is in NZ if that matters to anyone.
