### ISSUE TITLE
Add support for Deebot N8 Plus

### ISSUE THREAD

**Issue by albertoarmida** [DeebotUniverse/client.py#609]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

My Deebot N8 plus is no longer recognized with the latest version.
I saw that, with the new version, a model that is not explicitly supported is not added.
Before the update to the latest version it worked 100% so how can I help to include the Deebot N10 Plus starting from the default model? 

### On which deebot device (vacuum) you have the issue?

Deebot N8 Plus

### Which version of the deebot-client are you using?

9.1.0

### Country

it

### Continent

eu

**Comment by cdouet** [comment]
+1
Same issue

**Comment by Sobelix** [comment]
+1
Same issue
_Device info:
DEEBOT OZMO T8 (h18jkh)
by Ecovacs

Logger: homeassistant.components.ecovacs.controller
Source: components/ecovacs/controller.py:100
integration: Ecovacs (documentation, issues)
First occurred: 6:41:11 AM (2 occurrences)
Last logged: 6:46:47 AM

Device "DEEBOT OZMO T8" not supported. Please add support for it to https://github.com/DeebotUniverse/client.py:..._

**Comment by lnx85** [comment]
+1
Same issue here

**Comment by lnx85** [comment]
+1
Same issue

If you check out https://github.com/DeebotUniverse/client.py/pull/611 you can find a possible fix. I changed the instructions according to the different type of bot.

- Open HomeAssistant CLI (e.g. the console), and run login to get a shell prompt
- docker ps | grep homeassistant: - yes the colon is part of it!
- docker exec -it <CONTAINERID> sh - get the container ID from the start of the output above, it's a hex string
- cd /usr/local/lib/python3.13/site-packages/deebot_client/hardware/deebot
- ln -svfT x5d34r.py ty84oi.py
- Restart home assistant

**FOLLOW THESE AT YOUR OWN RISK TO TEST**

It works for me.

**Comment by edenhaus** [comment]
Please don't use the workaround; instead, please add your model to this library-
Instructions can be found https://github.com/DeebotUniverse/client.py/issues/612

**Comment by brendanm720** [comment]
I've just submitted a PR for this model.  It's #628.

**Comment by albertoarmida** [comment]
Great! I was thinking of working on it over the weekend.
Thank you!

**Comment by albertoarmida** [comment]
With 2024.12.1 the issue is solved.
