### ISSUE TITLE
Add support for DEEBOT X1 OMNI

### ISSUE THREAD

**Issue by caspre24** [DeebotUniverse/client.py#610]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

With the latest version used in HA 2024.12 the DEEBOT X1 OMNI is no longer accepted as supported.
It is listed at least as partially supported here https://deebot.readthedocs.io/home/models/ and was working in Home Assistant fine in version 2024.11.2.
Is there any chance we can get it enabled again, or what would be needed to get it supported again?

### On which deebot device (vacuum) you have the issue?

DEEBOT X1 OMNI

### Which version of the deebot-client are you using?

9.1.0

### Country

de

### Continent

eu

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant.components.ecovacs.controller
Source: components/ecovacs/controller.py:100
integration: Ecovacs (documentation, issues)
First occurred: 22:31:13 (2 occurrences)
Last logged: 22:34:35

Device "DEEBOT X1 OMNI" not supported. Please add support for it to https://github.com/DeebotUniverse/client.py: {'did': 'a33d645c-d5f2-4a7a-9f12-bd39b08a3d4f', 'name': 'E08D15513D1FP6ZG0063', 'class': '1vxt52', 'resource': 'k9S3', 'company': 'eco-ng', 'bindTs': 1698054057226, 'service': {'jmq': 'jmq-ngiot-eu.dc.ww.ecouser.net', 'mqs': 'api-ngiot.dc-eu.ww.ecouser.net'}, 'deviceName': 'DEEBOT X1 OMNI', 'icon': 'https://portal-ww.ecouser.net/api/pim/file/get/6225bd1c2af2127804f540e5', 'ota': True, 'UILogicId': 't10_ww_n_omni', 'materialNo': '110-2102-0300', 'pid': '6185e29610683da4d6a7a9cd', 'product_category': 'DEEBOT', 'model': 'EINSTEIN_INT', 'updateInfo': {'needUpdate': False, 'changeLog': ''}, 'nick': 'Robi', 'homeId': '63e53d58a55e944f97bf1eb1', 'homeSort': 1, 'status': 1, 'offmap': True, 'otaUpgrade': {}}


Logger: deebot_client.api_client
Source: components/ecovacs/controller.py:81
First occurred: 22:31:13 (2 occurrences)
Last logged: 22:34:35

Device class "1vxt52" not recognized. Please add support for it: {'did': '[REMOVED]', 'name': 'E08D15513D1FP6ZG0063', 'class': '1vxt52', 'resource': 'k9S3', 'company': 'eco-ng', 'bindTs': 1698054057226, 'service': {'jmq': 'jmq-ngiot-eu.dc.ww.ecouser.net', 'mqs': 'api-ngiot.dc-eu.ww.ecouser.net'}, 'deviceName': 'DEEBOT X1 OMNI', 'icon': 'https://portal-ww.ecouser.net/api/pim/file/get/6225bd1c2af2127804f540e5', 'ota': True, 'UILogicId': 't10_ww_n_omni', 'materialNo': '110-2102-0300', 'pid': '6185e29610683da4d6a7a9cd', 'product_category': 'DEEBOT', 'model': 'EINSTEIN_INT', 'updateInfo': {'needUpdate': False, 'changeLog': ''}, 'nick': 'Robi', 'homeId': '63e53d58a55e944f97bf1eb1', 'homeSort': 1, 'status': 1, 'offmap': True, 'otaUpgrade': {}}
```

**Comment by gdgib** [comment]
Check out https://github.com/DeebotUniverse/client.py/pull/611.  In addition to the PR there are some *VERY SKETCHY* instructions on how to temporarily hack the change into your HA install.  Use them at your own risk, but they did work for me.

**Comment by caspre24** [comment]
Interesting, I'll give that a shot 👍🏻
