### ISSUE TITLE
Please add support for DEEBOT OZMO T8 (h18jkh)

### ISSUE THREAD

**Issue by Dreweb** [DeebotUniverse/client.py#614]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

since the fallback for unsupported devices has cancelled, my device DEEBOT OZMO T8 (h18jkh) is no longer supported. 

With the fallback-solution ist just worked fine.
Please add support for this machine (similar to Deebot Ozmo T8+)

I had to downgrade my HA to Version 2024.11.3

### On which deebot device (vacuum) you have the issue?

DEEBOT OZMO T8 (h18jkh)

### Which version of the deebot-client are you using?

8.4.0

### Country

de

### Continent

eu

**Comment by immert20** [comment]
Same here.

**Comment by kotana** [comment]
Same here

**Comment by HxNetwork** [comment]
+1

**Comment by RSchipper** [comment]
This one seems to be added in https://github.com/DeebotUniverse/client.py/pull/638
