### ISSUE TITLE
Add support for T9+

### ISSUE THREAD

**Issue by bogorad** [DeebotUniverse/client.py#620]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

Device "DEEBOT T9+" not supported. Please add support for it to https://github.com/DeebotUniverse/client.py: 

```
{
  "did": "7200c027-78fa-44d7-a692-9cbb4268b847",
  "name": "E09G00724C09HKEW0291",
  "class": "um2ywg",
  "resource": "KjsJ",
  "company": "eco-ng",
  "bindTs": 1717142168835,
  "service": {
    "jmq": "jmq-ngiot-eu.dc.ww.ecouser.net",
    "mqs": "api-ngiot.dc-eu.ww.ecouser.net"
  },
  "deviceName": "DEEBOT T9+",
  "icon": "https://portal-ww.ecouser.net/api/pim/file/get/608b997e17c95b0008ff221f",
  "ota": true,
  "UILogicId": "T9_PRO_G",
  "materialNo": "110-2010-1102",
  "pid": "608b9981fc527c00087fddf1",
  "product_category": "DEEBOT",
  "model": "T9_PLUS_ECO_INT",
  "updateInfo": {
    "needUpdate": false,
    "changeLog": ""
  },
  "nick": "bobik",
  "homeId": "xx",
  "homeSort": 1,
  "status": 1,
  "offmap": true,
  "otaUpgrade": {}
}
```

### On which deebot device (vacuum) you have the issue?

T9+

### Which version of the deebot-client are you using?

latest in Home Assistant

### Country

ES

### Continent

EU

**Comment by marcolino7** [comment]
Hi, meanwhile here is a [workaround](https://github.com/DeebotUniverse/client.py/issues/607#issuecomment-2520922993)

**Comment by marcolino7** [comment]
Hi,
confitming that T9+ um2ywg work fine with T8 AIVI file x5d34r.py, someone can create a pull request? I am not be able to add a link to a PR.

Many thanks in advance

**Comment by marcolino7** [comment]
I created a specific Pull request for T9+ #632
