### ISSUE TITLE
Add support for DEEBOT T9 (ucn2xe)

### ISSUE THREAD

**Issue by marcomsousa** [DeebotUniverse/client.py#621]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

Support for DEEBOT T9 ucn2xe

Stopped worked now in HA 2024.12.0, before was worked sucesfully.

### On which deebot device (vacuum) you have the issue?

DEEBOT T9 ucn2xe

### Which version of the deebot-client are you using?

9.0.0

### Country

es

### Continent

eu

**Comment by marcolino7** [comment]
Hi, meanwhile here is a [workaround](https://github.com/DeebotUniverse/client.py/issues/607#issuecomment-2520922993)

**Comment by marcolino7** [comment]
Hi, I applied a workaround to my T9, please see here #611 and here [comment](https://github.com/DeebotUniverse/client.py/pull/611#issuecomment-2518897374)

You need to replace device class with yours

**Comment by edenhaus** [comment]
@marcolino7 Can you open a PR for it? Would be really nice to add them directly to the lib :)

**Comment by marcolino7** [comment]
> @marcolino7 Can you open a PR for it? Would be really nice to add them directly to the lib :)

Hi, I am not sure this is the right way. I have no competence to check all commands, and I am not sure that T9 is fully compatible with T10. For example in Home Assistant entity, room list is empty.
This is an emergency workaround meanwhile a fully compatible addon will be found.

Thanks

**Comment by marcomsousa** [comment]
`Logger: homeassistant.components.ecovacs.controller
Source: components/ecovacs/controller.py:100
integration: Ecovacs (documentation, issues)
First occurred: 9:20:18 PM (1 occurrences)
Last logged: 9:20:18 PM

Device "DEEBOT T9" not supported. More information at https://github.com/DeebotUniverse/client.py/issues/612: {'did': '60.....', 'name': 'E03400...... Si', 'class': 'ucn2xe', 'resource': '2vPL', 'company': 'eco-ng', 'bindTs': 1721648475469, 'service': {'jmq': 'jmq-ngiot-eu.dc.ww.ecouser.net', 'mqs': 'api-ngiot.dc-eu.ww.ecouser.net'}, 'deviceName': 'DEEBOT T9', 'icon': 'https://portal-ww.ecouser.net/api/pim/file/get/6.....', 'ota': True, 'UILogicId': 'T9_PRO_G', 'materialNo': '110-2010-0301', 'pid': '5f8........', 'product_category': 'DEEBOT', 'model': 'DEEBOT_OZMO_T9', 'updateInfo': {'needUpdate': False, 'changeLog': ''}, 'nick': 'Robot', 'homeId': '6....', 'homeSort': 1, 'status': 1, 'offmap': True, 'otaUpgrade': {}}`
