### ISSUE TITLE
Add Support to Ecovacs Deebot U2 Pro

### ISSUE THREAD

**Issue by willliamchan** [DeebotUniverse/client.py#629]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

To Add support for Deebot U2 Pro

### On which deebot device (vacuum) you have the issue?

Deebot U2 Pro

### Which version of the deebot-client are you using?

9.1.0

### Country

uk

### Continent

eu

### Additional information

Hi Greg (@gdgib ), I can confirm the same procedure works for Ecovacs U2 PRO (7j1tu6). What I did was to use the same one-liner and had 1vxt52.py replaced with 7j1tu6.py, reboot HA and I am completely back in the game.

While U2 Pro is just a basic robot vacuum and lacks features like X1 Omni, the below should be removed.

**Configuration**
Map - _Map is not available even from Ecovacs App_
Advanced Mode
Carpet Auto-Boost Suction
Clean Count
Clean Preference
Continuous Cleaning
Reset main brush lifespan
Reset round mop lifespan
Reset unit care lifespan
True detect

**Diagnostic**
Round mop lifespan
Unit care lifespan

Thank you in advance!

**Comment by edenhaus** [comment]
I mentioned you in https://github.com/DeebotUniverse/client.py/pull/623 Please answer my question there and than we can merge it
