### ISSUE TITLE
Add support for DEEBOT OZMO T8+ (fqxoiu)

### ISSUE THREAD

**Issue by Jimtb** [DeebotUniverse/client.py#634]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

My DEEBOT OZMO T8+ is no longer recognized with the latest update.

Before the update the T8+ worked 100% fine with the fallback option. 

### On which deebot device (vacuum) you have the issue?

DEEBOT OZMO T8+

### Which version of the deebot-client are you using?

latest

### Country

NL

### Continent

eu

### Anything in the logs that might be useful for us?

```txt
`Device "DEEBOT OZMO T8+" not supported. Please add support for it to https://github.com/DeebotUniverse/client.py: 
{
'did': 'xxx',
 'name': 'xxx',
 'class': 'fqxoiu',
 'resource': 'KUUy', 
'company': 'eco-ng',
 'bindTs': 1698043818268,
 'service': {
	'jmq': 'jmq-ngiot-eu.dc.ww.ecouser.net',
	'mqs': 'api-ngiot.dc-eu.ww.ecouser.net'
	},
'deviceName': 'DEEBOT OZMO T8+', 
'icon': 'https://portal-ww.ecouser.net/api/pim/file/get/605b059217c95b0008ff20d4',
 'ota': True,
 'UILogicId': 'DT_8G', 
 'materialNo': '110-1921-1100',
 'pid': '5e8e8d8a032edd8457c66bfb',
 'product_category': 'DEEBOT', 
 'model': 'OT8+', 
 'updateInfo': 
 {
'needUpdate': False, 
 'changeLog': ''}
 , 'nick': 'xxx',
 'homeId': 'xxx', 
 'homeSort': 9999, 
 'status': 1, 
 'offmap': True,
 'otaUpgrade': {}
}`
```

**Comment by Jimtb** [comment]
The label should be enhancement instead of bug but I cant seem to change it.

**Comment by edenhaus** [comment]
Added with #639
