### ISSUE TITLE
Add support for DEEBOT T30 PRO OMNI

### ISSUE THREAD

**Issue by niclas911** [DeebotUniverse/client.py#643]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

After updating Home Assistant to:
Core: 2024.12.1
(Supervisor 2024.11.4
Operating System: 14.0)

The DEEBOT T30 PRO OMNI (Firmware 1.87.0) is no longer accessible, and no entities are available. Before the Home Assistant update, the integration worked very well. Could you please add this vacuum cleaner back again?

### On which deebot device (vacuum) you have the issue?

DEEBOT T30 PRO OMNI

### Which version of the deebot-client are you using?

Newest

### Country

De

### Continent

Eu

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant.components.ecovacs.controller
Quelle: components/ecovacs/controller.py:100
Integration: Ecovacs (Dokumentation, Probleme)
Erstmals aufgetreten: 15:33:55 (2 Vorkommnisse)
Zuletzt protokolliert: 17:14:08

Device "DEEBOT T30 PRO OMNI" not supported. More information at https://github.com/DeebotUniverse/client.py/issues/612: {'did': 'a4a212a6-168f-49bd-8d8d-993eb67bd0f8', 'name': 'E02S32242F1FPKNC0295', 'class': 'tlthqk', 'resource': '1Ft9', 'company': 'eco-ng', 'bindTs': 1721743490329, 'service': {'jmq': 'jmq-ngiot-eu.dc.ww.ecouser.net', 'mqs': 'api-ngiot.dc-eu.ww.ecouser.net'}, 'deviceName': 'DEEBOT T30 PRO OMNI', 'icon': 'https://portal-ww.ecouser.net/api/pim/file/get/65e03fdda16bb4e6c79e8017', 'ota': True, 'UILogicId': 't30pro_ww_h_t30h5', 'materialNo': '110-2330-0209', 'pid': '65d83a49b4e54abe7096a514', 'product_category': 'DEEBOT', 'model': 'T30_PRO_INT_MILKTEA', 'updateInfo': {'needUpdate': False, 'changeLog': ''}, 'nick': None, 'homeId': '669fb7e513b75c2b182ad4d4', 'homeSort': 1, 'status': 1, 'offmap': True, 'btName': 'ECOVACS-tlthqk-0295', 'btMac': '64:82:14:0D:F6:0F', 'otaUpgrade': {}}
```

**Comment by niclas911** [comment]
Logger: deebot_client.api_client
Quelle: components/ecovacs/controller.py:81
Erstmals aufgetreten: 18:10:45 (3 Vorkommnisse)
Zuletzt protokolliert: 18:17:51

Device class "tlthqk" not recognized. Please add support for it: {'did': '[REMOVED]', 'name': 'E02S32242F1FPKNC0295', 'class': 'tlthqk', 'resource': '1Ft9', 'company': 'eco-ng', 'bindTs': 1721743490329, 'service': {'jmq': 'jmq-ngiot-eu.dc.ww.ecouser.net', 'mqs': 'api-ngiot.dc-eu.ww.ecouser.net'}, 'deviceName': 'DEEBOT T30 PRO OMNI', 'icon': 'https://portal-ww.ecouser.net/api/pim/file/get/65e03fdda16bb4e6c79e8017', 'ota': True, 'UILogicId': 't30pro_ww_h_t30h5', 'materialNo': '110-2330-0209', 'pid': '65d83a49b4e54abe7096a514', 'product_category': 'DEEBOT', 'model': 'T30_PRO_INT_MILKTEA', 'updateInfo': {'needUpdate': False, 'changeLog': ''}, 'nick': None, 'homeId': '669fb7e513b75c2b182ad4d4', 'homeSort': 1, 'status': 1, 'offmap': True, 'btName': 'ECOVACS-tlthqk-0295', 'btMac': '64:82:14:0D:F6:0F', 'otaUpgrade': {}}

**Comment by RSchipper** [comment]
Created the PR for you: https://github.com/DeebotUniverse/client.py/pull/664

**Comment by niclas911** [comment]
@edenhaus @RSchipper 

I want to express my heartfelt appreciation for the volunteer support. The response was not only incredibly quick but also exceptionally friendly – it truly overwhelmed me.

I can only imagine how much time and effort you dedicate to this work. But it’s people like you who enable a large project like Home Assistant to not only survive but also continuously function and grow.

Thank you for your commitment and support – you truly make a difference!

**Comment by RSchipper** [comment]
Thank you for your kind words.

Most appreciation should go to @edenhaus and other maintainers of this project and HomeAssistant. I merely try to help by combing the issues once every now and then and create PRs of the well-written ones.

**Comment by edenhaus** [comment]
Model was added with https://github.com/DeebotUniverse/client.py/pull/666
