### ISSUE TITLE
Add support for Deebot N10 m1wkuw

### ISSUE THREAD

**Issue by slartibartfast11** [DeebotUniverse/client.py#647]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

Please add support for Deebot N10 model m1wkuw.

I have tested on my Home Assistant instance by linking to m1wkuw.py from the existing similar model N10 Plus driver umwv6z.py. All expected functionality works, except that the N10 does not support TrueDetect.

### On which deebot device (vacuum) you have the issue?

Deebot N10

### Which version of the deebot-client are you using?

9.2.0 / 2024.12.1

### Country

AU

### Continent

WW

**Comment by Eraldometris** [comment]
Can we just set up a symbolic link to umwv6z.py? 

Or, would it be more appropriate to copy into its own driver and remove true detect? 

@edenhaus @slartibartfast11 how do you guys want to proceed?

**Comment by edenhaus** [comment]
The reason for the capabilities file is to map the model correctly. Symbolic link can only be used if the models have the same capabilities, which is not the case here. I created the PR for you

**Comment by Eraldometris** [comment]
> The reason for the capabilities file is to map the model correctly. Symbolic link can only be used if the models have the same capabilities, which is not the case here. I created the PR for you

Thank you so much @edenhaus. Really appreciate it 🙌
