### ISSUE TITLE
Add support for Deebot N30 pro Omni (87swps)

### ISSUE THREAD

**Issue by jbdjool** [DeebotUniverse/client.py#660]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

When I updated to HA 2024.12.x and HA told me that which is not supported.

### On which deebot device (vacuum) you have the issue?

Deebot N30 pro Omni

### Which version of the deebot-client are you using?

Latest

### Country

FR

### Continent

EU

### Anything in the logs that might be useful for us?

```txt
Device class "87swps" not recognized. Please add support for it
deviceName : DEEBOT N30 PRO OMNI
```

### Additional information

This vaccum is similar to N30 Omni which is supported, difference is only the hot water mopping read from Ecovacs website.
I'm not good to build a test setup...

**Comment by RSchipper** [comment]
Created the PR for you: https://github.com/DeebotUniverse/client.py/pull/663

**Comment by jbdjool** [comment]
thanks ! is there something i can do for help in testing with my little knowledge ?
