### ISSUE TITLE
Add support for DEEBOT N8 BLACK

### ISSUE THREAD

**Issue by marmer1** [DeebotUniverse/client.py#670]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

The model (7zya6u) is not longer supported by the integration.

### On which deebot device (vacuum) you have the issue?

DEEBOT N8 BLACK 7zya6u

### Which version of the deebot-client are you using?

9.3.0

### Country

at

### Continent

eu

**Comment by reuz** [comment]
I too would like support for the N8 Black. I am willing to test edits and provide logging if needed.

**Comment by marmer1** [comment]
After adding the symlink from 7zya6u.py to x5d34r.py, the integration is now working as expected with all provided entities. However, I am unable to run the provided tests locally due to my limited experience. Any guidance or assistance with this would be greatly appreciated. Thank you!

**Comment by reuz** [comment]
> After adding the symlink from 7zya6u.py to x5d34r.py, the integration is now working as expected with all provided entities. However, I am unable to run the provided tests locally due to my limited experience. Any guidance (which tests are required to run) or assistance with this would be greatly appreciated. Thank you!

Stupid question probably. But where can I find these files @marmer1

**Comment by reuz** [comment]
In regards to testing. I can verify that this file works. It comes back with all the sensors and everything after restarting Home Assistant. My buttons and sensors I used immidiately work again. So @edenhaus linking the file works as expected and makes it work again. So it might be just a matter of copying the file.
