### ISSUE TITLE
Add support for DEEBOT N20 PLUS

### ISSUE THREAD

**Issue by murgalicious** [DeebotUniverse/client.py#671]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

The model "buom7k" is not supported - would love it to be! 
Please tell me if there is anything I can do to help. 

### On which deebot device (vacuum) you have the issue?

DEEBOT N20 PLUS

### Which version of the deebot-client are you using?

9.3.0

### Country

SE

### Continent

EU

### Anything in the logs that might be useful for us?

```txt
Device class "buom7k" not recognized. Please add support for it: {'did': '[REMOVED]', 'name': 'E07C32617F1FPMYB0112', 'class': 'buom7k', 'resource': 'NMBM', 'company': 'eco-ng', 'bindTs': 1733941433851, 'service': {'jmq': 'jmq-ngiot-eu.dc.ww.ecouser.net', 'mqs': 'api-ngiot.dc-eu.ww.ecouser.net'}, 'deviceName': 'DEEBOT N20 PLUS', 'icon': 'https://portal-ww.ecouser.net/api/pim/file/get/664312f5028bb26d95ab10f9', 'ota': True, 'UILogicId': 'y2se_ww_h_y2h5', 'materialNo': '110-2408-0001', 'pid': '65fa42bcb895cd3c4796362b', 'product_category': 'DEEBOT', 'model': 'Y2_AES_LITE_INT', 'updateInfo': {'needUpdate': False, 'changeLog': ''}, 'nick': 'guttis', 'homeId': '6758bc08eb71ed6cf3c7f05c', 'homeSort': 1, 'status': 1, 'offmap': True, 'otaUpgrade': {}}
```

**Comment by edenhaus** [comment]
This model was added with #669
