### ISSUE TITLE
Add support Deebot OZMO T8 AIVI

### ISSUE THREAD

**Issue by eight10man** [DeebotUniverse/client.py#672]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

My T8 AIVI stopped being supported. Device class = bs40nz

Device "DEEBOT T8 AIVI" not supported. More information at https://github.com/DeebotUniverse/client.py/issues/612: {'did': '738fa963-33fa-4a5d-bc4b-e25426f05b25', 'name': 'E0BQ13731B09HFX90444', 'class': 'bs40nz', 'resource': 'AFwx', 'company': 'eco-ng', 'bindTs': 1697011265872, 'service': {'jmq': 'jmq-ngiot-cn.dc.cn.ecouser.net', 'mqs': 'api-ngiot.dc-cn.cn.ecouser.net'}, 'deviceName': 'DEEBOT T8 AIVI', 'icon': 'https://portal.ecouser.net/api/pim/file/get/604efc0df49feb0008d0c93e', 'ota': True, 'UILogicId': 'DX_AI', 'materialNo': '110-1913-0002', 'pid': '5de0d6658c8297000142b807', 'product_category': 'DEEBOT', 'model': 'DXAI', 'updateInfo': {'needUpdate': False, 'changeLog': ''}, 'nick': 'Bobby', 'homeId': '6260bb644f20d923f8fab0f9', 'homeSort': 1, 'status': 1, 'offmap': True, 'otaUpgrade': {}}

### On which deebot device (vacuum) you have the issue?

Deebot OZMO T8 AIVI

### Which version of the deebot-client are you using?

HA 2024.12.2

### Country

China

### Continent

China

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant.components.ecovacs.controller
Source: components/ecovacs/controller.py:100
integration: Ecovacs (documentation, issues)
First occurred: 10:53:34 AM (1 occurrences)
Last logged: 10:53:34 AM
Device "DEEBOT T8 AIVI" not supported. More information at https://github.com/DeebotUniverse/client.py/issues/612: {'did': '738fa963-33fa-4a5d-bc4b-e25426f05b25', 'name': 'E0BQ13731B09HFX90444', 'class': 'bs40nz', 'resource': 'AFwx', 'company': 'eco-ng', 'bindTs': 1697011265872, 'service': {'jmq': 'jmq-ngiot-cn.dc.cn.ecouser.net', 'mqs': 'api-ngiot.dc-cn.cn.ecouser.net'}, 'deviceName': 'DEEBOT T8 AIVI', 'icon': 'https://portal.ecouser.net/api/pim/file/get/604efc0df49feb0008d0c93e', 'ota': True, 'UILogicId': 'DX_AI', 'materialNo': '110-1913-0002', 'pid': '5de0d6658c8297000142b807', 'product_category': 'DEEBOT', 'model': 'DXAI', 'updateInfo': {'needUpdate': False, 'changeLog': ''}, 'nick': 'Bobby', 'homeId': '6260bb644f20d923f8fab0f9', 'homeSort': 1, 'status': 1, 'offmap': True, 'otaUpgrade': {}}


Logger: deebot_client.api_client
Source: components/ecovacs/controller.py:81
First occurred: 10:53:34 AM (1 occurrences)
Last logged: 10:53:34 AM
Device class "bs40nz" not recognized. Please add support for it: {'did': '[REMOVED]', 'name': 'E0BQ13731B09HFX90444', 'class': 'bs40nz', 'resource': 'AFwx', 'company': 'eco-ng', 'bindTs': 1697011265872, 'service': {'jmq': 'jmq-ngiot-cn.dc.cn.ecouser.net', 'mqs': 'api-ngiot.dc-cn.cn.ecouser.net'}, 'deviceName': 'DEEBOT T8 AIVI', 'icon': 'https://portal.ecouser.net/api/pim/file/get/604efc0df49feb0008d0c93e', 'ota': True, 'UILogicId': 'DX_AI', 'materialNo': '110-1913-0002', 'pid': '5de0d6658c8297000142b807', 'product_category': 'DEEBOT', 'model': 'DXAI', 'updateInfo': {'needUpdate': False, 'changeLog': ''}, 'nick': 'Bobby', 'homeId': '6260bb644f20d923f8fab0f9', 'homeSort': 1, 'status': 1, 'offmap': True, 'otaUpgrade': {}}
```

**Comment by edenhaus** [comment]
This model was added with #665
