### ISSUE TITLE
Please add support for DEEBOT N8 BLACK (7zya6u)

### ISSUE THREAD

**Issue by THGit26** [DeebotUniverse/client.py#720]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

After updating Homeassistant to Core 12.5 (I tried from 12.0 upwards the last weeks), my Deebot is not working any logner.

I followed the discussions about the update from 12.0 on and I would kindly ask if somebode can configure the DEEBOT N8 BLACK (7zya6u) into the Ecovacs solution.

I am sorry, but I do not know how to add my device type to the library (https://github.com/DeebotUniverse/client.py).

Now, after updating to Homeassistant Core 12.5 I got my Deebot running by using the workaround (https://github.com/DeebotUniverse/client.py/pull/632#issuecomment-2538380467), but I think this should not be the solution for forever.

### On which deebot device (vacuum) you have the issue?

DEEBOT N8 BLACK (7zya6u)

### Which version of the deebot-client are you using?

9.4.0 (I hope this is right, searched a longer time and found it in Ecovacs AddIn Diagnostics)

### Country

DE

### Continent

eu

### Anything in the logs that might be useful for us?

```txt
Sorry, I now got the workaround working and lost the prior logs :(

But it is the same as all people using not supported Deebots.
```

### Additional information

From Diagnostics

devices": [
      {
        "did": "**REDACTED**",
        "name": "**REDACTED**",
        "class": "7zya6u",
        "resource": "1Hiw",
        "company": "eco-ng",
        "bindTs": 1726590353165,
        "service": {
          "jmq": "jmq-ngiot-eu.dc.ww.ecouser.net",
          "mqs": "api-ngiot.dc-eu.ww.ecouser.net"
        },
        "deviceName": "DEEBOT N8 BLACK",
        "icon": "https://portal-ww.ecouser.net/api/pim/file/get/6243b185784d1652c082ef31",
        "ota": true,
        "UILogicId": "N8_PLUS",
        "materialNo": "<DELETED>",
        "pid": "<DELETED>",
        "product_category": "DEEBOT",
        "model": "N8_BLACK_EMEA",
        "updateInfo": {
          "needUpdate": false,
          "changeLog": ""
        },
        "nick": "<DELETED>",
        "homeId": "**REDACTED**",
        "homeSort": 1,
        "status": 1,
        "offmap": true,
        "otaUpgrade": {}
      }

**Comment by marmer1** [comment]
The device is already included in release 10.0.1
Check out pr #686
